[config]
# version_check = true

[templates.hyprland]
input_path = '~/.config/matugen/matugen-themes/templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.waybar]
input_path = '~/.config/matugen/matugen-themes/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = '~/.config/waybar/scripts/refresh.sh'

[templates.dunst]
input_path = '~/.config/matugen/matugen-themes/templates/dunstrc-colors'
output_path = '~/.config/dunst/dunstrc'

[templates.wlogout]
input_path = '~/.config/matugen/matugen-themes/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'
post_hook = '~/.config/waybar/scripts/refresh.sh'
